### ISSUE TITLE
"ImportError: No module named dxr"

### ISSUE THREAD

**Issue by fitzgen** [Osmose/dxr-cmd#2]
Ok, so I installed it successfully via https://github.com/Osmose/dxr-cmd/issues/1#issuecomment-116767836 and when I run it, I get this:

```
$ dxr AbstractFramePtr
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/dxr", line 9, in <module>
    load_entry_point('dxr-cmd==0.1', 'console_scripts', 'dxr')()
  File "build/bdist.macosx-10.6-intel/egg/pkg_resources.py", line 357, in load_entry_point
  File "build/bdist.macosx-10.6-intel/egg/pkg_resources.py", line 2394, in load_entry_point
  File "build/bdist.macosx-10.6-intel/egg/pkg_resources.py", line 2108, in load
ImportError: No module named dxr
```

**Comment by Osmose** [comment]
I was able to replicate (turns out just testing your local development install isn't enough, who knew?) and found that I had screwed up telling setup.py how to find dxr.py. Oops.

@fitzgen Can you verify if this is fixed for you? You might need to `pip uninstall dxr-cmd` and re-install to get the fix.

**Comment by fitzgen** [comment]
Confirmed fixed! Thanks!

_Nick_
