### ISSUE TITLE
dxr stopped working

### ISSUE THREAD

**Issue by tromey** [Osmose/dxr-cmd#5]
dxr stopped working recently.  I get:

```
pokyo. dxr SavedStacks
Traceback (most recent call last):
  File "/home/tromey/bin/scripts/dxr", line 9, in <module>
    load_entry_point('dxr-cmd==0.2.0', 'console_scripts', 'dxr')()
  File "/home/tromey/dxr-cmd/lib/python2.7/site-packages/dxr.py", line 68, in main
    response_json = response.json()
  File "/home/tromey/dxr-cmd/lib/python2.7/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

I asked on #static and they said that "format=json" no longer works; instead you have to send the appropriate Accept header.

**Comment by Osmose** [comment]
Fixed! I released 0.2.2 with this fix (as well as a fix for passing the incorrect values for case-insensitive search). Let me know if it's working for you!
